version: '3'
services:
  web:
    stdin_open: true # https://github.com/facebook/create-react-app/issues/8688
    build:
      context: . # maps the context to the current folder where the app is located
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app      # maping the current app directory to the running container for automatic code reloading
  tests:
    stdin_open: true # https://github.com/facebook/create-react-app/issues/8688
    build:
      context: . # maps the context to the current folder where the app is located
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app # maping the current app directory to the running container for automatic code reloading
    command: ["npm", "run", "test"]
